### PR TITLE
Add reopen method for channel

### PR DESCRIPTION
**Pull request by decaz**
It happens that the channel closes and you need to open it again. In case of robust connection currently this is possible using an inconvenient call:
```python
await channel.on_reconnect(
    connection=channel._connection,
    channel_number=channel._channel_number,
)
```
I suggest to make it as follows:
```python
await channel.reopen()
```
Thereby `on_reconnect` methods should be renamed to `restore` which mean more broad sense than just reconnection.

### CODE REVIEW

**Comment by mosquito** [comment]
@decaz you have to write some tests for reopening a closed channel

**Comment by mosquito** [comment]
But tests 😟

**Comment by decaz** [comment]
@mosquito I didn't requested a review yet :) Just rebased againt the master branch.

**Comment by mosquito** [comment]
Ok. Looking forward tests

**Comment by decaz** [comment]
@mosquito I've added a little test. What do you think?

**Comment by decaz** [comment]
@mosquito any thoughts?

**Comment by mosquito** [comment]
Hi there. Current plan is make a new release after new year holidays. I'm so busy sorry.

**Pull request merged**
