### PR TITLE
Remove not needed creation of new dict

### PR DESCRIPTION
**Pull request by heckad**

### CODE REVIEW

**Comment by Gera3dartist** [comment]
won't this change,  create a reference to `self.headers._headers` instead of copying it?

**Comment by heckad** [comment]
No, look at the Message constructor. 
```
        self.headers_raw = format_headers(headers)
        self._headers = HeaderProxy(self.headers_raw)
```
And format_headers
```
def format_headers(d: Dict[str, Any]) -> Dict[str, bytes]:
    ret = {}

    if not d:
        return ret

    for key, value in d.items():
        ret[key] = header_converter(value)
    return ret
```
We creates new  dict again!

**Comment by heckad** [comment]
@mosquito?

**Comment by mosquito** [comment]
Do not understand why is safe. The copied message can modify headers and original headers will be modified too.

**Comment by heckad** [comment]
No, you do copy twice: in __copy__ and in format_headers.

**Comment by mosquito** [comment]
Oh, my fail.

**Pull request merged**
