### PR TITLE
Add note about asyncio event loop

### PR DESCRIPTION
**Pull request by maxnordlund**
This is a hard requirement and will probably get new developers if not mentioned early.

### CODE REVIEW

**Comment by mosquito** [comment]
By default, event `loop` argument not required. If loop not passed will be called `asyncio.get_event_loop()`

**Comment by maxnordlund** [comment]
But you still need the `loop.run_until_complete`, right?

**Comment by mosquito** [comment]
Lets add it into examples.

**Comment by maxnordlund** [comment]
I don't quite follow, do you mean add a new example or something else?

**Comment by mosquito** [comment]
Ok, my point is [this example](https://aio-pika.readthedocs.io/en/latest/rabbitmq-tutorial/1-introduction.html#putting-it-all-together) already has it. 
If you want to add some info about event loop (and asyncio of course), just add it as a different note block. Add link to the [asyncio tutorial](https://pymotw.com/3/asyncio/coroutines.html) or [python documentation](https://docs.python.org/3/library/asyncio.html)

**Comment by mosquito** [comment]
@maxnordlund what did you think [changes in warning block](https://aio-pika.readthedocs.io/en/latest/rabbitmq-tutorial/1-introduction.html#introduction) closed this issue?

**Comment by maxnordlund** [comment]
Yeah that's better, but I do think a reminder in the quickstart doesn't hurt. Feel free to close this if you want.

**Pull request closed without merging**
