### PR TITLE
Add robust parameters

### PR DESCRIPTION
**Pull request by decaz**
As it is already done for `RobustChannel.declare_exchange` and `RobustChannel.declare_queue`.

### CODE REVIEW

**Comment by decaz** [comment]
@mosquito any thoughts?

**Comment by mosquito** [comment]
I want to add some tests for this but not imagine how.

**Comment by decaz** [comment]
@mosquito maybe it can be merged for now as it was done at #95 ?

**Comment by mosquito** [comment]
please add following test case

```python
class TestCaseNoRobust(AMQPTestCase):
    async def create_connection(self, cleanup=True) -> Connection:
        client = await connect_robust(str(AMQP_URL), loop=self.loop)
        if cleanup:
            self.addCleanup(client.close)
        return client

    async def create_channel(self, connection=None,
                             cleanup=True, **kwargs) -> Channel:
        return await super().create_channel(
            cleanup=cleanup, robust=False
        )

    async def declare_queue(self, *args, **kwargs) -> Queue:
        kwargs = kwargs.copy()
        kwargs['robust'] = False
        return await super().declare_queue(*args, **kwargs)

    async def declare_exchange(self, *args, **kwargs) -> Exchange:
        kwargs = kwargs.copy()
        kwargs['robust'] = False
        return await super().declare_exchange(*args, **kwargs)
```

**Comment by decaz** [comment]
@mosquito done.

**Pull request merged**
