### PR TITLE
Fix reconnecting on a closed connection

### PR DESCRIPTION
**Pull request by heckad**
https://github.com/mosquito/aio-pika/issues/305#issuecomment-601619158

### CODE REVIEW

**Comment by vashchukmaksim** [comment]
It solved RobustConnection error for me!

But still I got `aiormq.exceptions.DeliveryError`. Likely it is because of my setup but I can not figure it out. Could you take a look please? Here is a test repo: https://github.com/vashchukmaksim/quart-aio-pika-example

**Comment by heckad** [comment]
You are not run consumer. You are run asgi app. Execute `docker exec -it  quartaiopikaexample_consumer_1 ps aux` and look at the run command. They will be 
```
appuser      1  0.0  0.1   5488  2016 ?        Ss   22:03   0:00 /bin/bash /home/appuser/app/server/run_asgi.sh /home/appuser/app/server/run_consumer.sh```
Use entrypoint insted of command. I made pull request.

**Comment by vashchukmaksim** [comment]
My bad... Thank you! All works perfectly

**Comment by heckad** [comment]
@mosquito ?

**Comment by heckad** [comment]
@mosquito?

**Comment by tsaridas** [comment]
is this merged but not released ?

**Pull request merged**
