### PR TITLE
The callback function can be a coroutine

### PR DESCRIPTION
**Pull request by iselind**

### CODE REVIEW

**Comment by mosquito** [comment]
Great work. Thank you.

**Comment by mosquito** [comment]
Your changes was applied to release 0.19.0.

**Comment by iselind** [comment]
When will the docs at https://aio-pika.readthedocs.io/en/latest/rabbitmq-tutorial/1-introduction.html be regenerated?

**Comment by mosquito** [comment]
@iselind as soon as readthedocs will made it.

**Comment by mosquito** [comment]
BTW: I found some issues with line numbers in rst-file. But I already fix it.

**Comment by iselind** [comment]
Ops, very sorry i missed that!

**Pull request merged**
