### PR TITLE
Add context manager to channel

### PR DESCRIPTION
**Pull request by shanecarey17**

### CODE REVIEW

**Comment by mosquito** [comment]
Please add some tests for this behavior. I guess this should fail when __aexit__ will be called after `ChannelClosed` exception.

**Comment by mosquito** [comment]
The tests were failed. Will you improve this change set? Is this still actual?

**Comment by shanecarey17** [comment]
Hi, I will improve this changeset, have not had the time recently.

**Comment by mosquito** [comment]
Please reopen this PR when you finished.

**Pull request closed without merging**
