### PR TITLE
Avoid depending on `typing_extensions` where not needed

### LINKED ISSUE #649: ModuleNotFoundError: No module named 'typing_extensions'
Using `aio-pika 9.5.0`
Summed up in one image:

Screenshot From 2024-11-22 11-52-48

Bug introduced by #615 in v9.5.0

### PR DESCRIPTION
**Pull request by zware**
Fixes #649 (I think :slightly_smiling_face:)

### CODE REVIEW

**Comment by zware** [comment]
Now with more surety, fixes #649 :)

**Review by mosquito — APPROVED** [review]

**Comment by zware** [comment]
Not really sure what happened (looks like `master` was force-pushed?), but now rebased.

**Comment by zware** [comment]
Not a whole lot of point to this after 36cdae8.

**Comment by mosquito** [comment]
Oh, sorry, I should have written something here.

**Comment by zware** [comment]
No problem, just glad a clean version is released :)

**Pull request closed without merging**
