### PR TITLE
Add missing connection timeout parameter

### PR DESCRIPTION
**Pull request by decaz**
Some type hints were also fixed.

### CODE REVIEW

**Comment by mosquito** [comment]
Looks so complex against `asyncio.wait_for(connect(), timeout=1)`

**Comment by decaz** [comment]
@mosquito there is already at low-level:
https://github.com/mosquito/aio-pika/blob/83bf56db507a8a88eb80dce353067c608134a76a/aio_pika/connection.py#L116-L119
but high-level `connect` and `connect_robust` doesn't have `timeout` parameter to propagate timeout to the lower level, - that is what this PR for.

**Comment by mosquito** [comment]
@decaz you are right.

**Comment by mosquito** [comment]
version 6.1.1 already released

**Pull request merged**
